# Generated by Django 5.2.3 on 2025-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('reclamacao', 'Reclamação'), ('elogio', 'Elogio'), ('sugestao', 'Sugestão')], max_length=20)),
                ('categoria', models.CharField(choices=[('transporte', 'Transporte Público'), ('vias', 'Vias Urbanas'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em análise', 'Em análise'), ('Em execução', 'Em execução'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
            ],
        ),
    ]
